/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bouncyballs;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import java.util.Set;
import javax.swing.Timer;

/**
 *
 * @author Collin Shook
 */
public class Frame1 extends javax.swing.JFrame {

    
    
    Timer PanelTimer;
    boolean TimerStatus;
    Random RNG = new Random();
    
    // ball info
    int radius = 45;
    int x = 1;
    int y = 1;
    
    int angle = 315;
    
    int clockTick = 30;
    
    ArrayList<Ball> balls = new ArrayList();
    
    Random RNG2 = new Random();
    
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        
        TimerStatus = false;
        
        this.setLocationRelativeTo(null);
        this.setTitle("Bouncing Balls");
        
        
    }
    
    public void PanelClock()
    {
        PanelTimer = new Timer(clockTick, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPanel1.repaint();
                
            }
        });
        
        PanelTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBttnAddBall = new javax.swing.JButton();
        jBttnRemoveLastBall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jBttnAddBall.setText("Add Ball");
        jBttnAddBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddBallActionPerformed(evt);
            }
        });

        jBttnRemoveLastBall.setText("Remove Last Ball");
        jBttnRemoveLastBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnRemoveLastBallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jBttnAddBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBttnRemoveLastBall)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnAddBall)
                    .addComponent(jBttnRemoveLastBall)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddBallActionPerformed
        // TODO add your handling code here:
        
        // ball characteristics
        
        Ball myBall = new Ball();
        
        myBall.setVisible(true);
        
        myBall.setRadius(RNG.nextInt(36) + 10);
        
        Color randomColor = new Color(RNG.nextInt(256),RNG.nextInt(256), RNG.nextInt(256));
        myBall.setBallColor(randomColor);
        
        myBall.setPanelWidth(jPanel1.getWidth());
        myBall.setPanelHeight(jPanel1.getHeight());
        
        myBall.setxPos(0);
        myBall.setyPos(0);
        
        myBall.setAngle(RNG.nextInt(89) + 271); // random angle from 271 to 359 degrees reference to unit circle
        
        myBall.setSize(jPanel1.getWidth(), jPanel1.getHeight());
        
        myBall.setSpeed(RNG.nextInt(96) + 5);
        
        
        // add ball to panel and array
        
        jPanel1.add(myBall);
        
        balls.add(myBall);
        
        myBall.startBall();
        
        if(!TimerStatus)
        {
            PanelClock();
            TimerStatus = true;
        }
    }//GEN-LAST:event_jBttnAddBallActionPerformed

    private void jBttnRemoveLastBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnRemoveLastBallActionPerformed
        // TODO add your handling code here:
        try
        {
            jPanel1.remove(balls.size() - 1);
            balls.remove(balls.size() - 1);
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_jBttnRemoveLastBallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAddBall;
    private javax.swing.JButton jBttnRemoveLastBall;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
