/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package combobox;

import java.awt.event.KeyEvent;

/**
 *
 * @author collinshook
 */
public class Frame1 extends javax.swing.JFrame
{


String[] Comedians = {"Larry", "Curly", "Moe", "Shemp", "Curly Joe"};

/**
 * Creates new form Frame1
 */
public Frame1()
{
    initComponents();
    
    
    jcmboComedians.removeAllItems();
    
    for (String comedian : Comedians)
    {
        jcmboComedians.addItem(comedian);
    }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jcmboComedians = new javax.swing.JComboBox<>();
        jtxtInput = new javax.swing.JTextField();
        jbttnRemoveLast = new javax.swing.JButton();
        jbttnAddItem = new javax.swing.JButton();
        jbttnRemoveSelected = new javax.swing.JButton();
        jlblSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(20, 20, 20));
        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setText("Comedians");

        jcmboComedians.setBackground(new java.awt.Color(20, 20, 20));
        jcmboComedians.setForeground(new java.awt.Color(225, 225, 225));
        jcmboComedians.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmboComedians.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcmboComediansActionPerformed(evt);
            }
        });

        jtxtInput.setBackground(new java.awt.Color(20, 20, 20));
        jtxtInput.setForeground(new java.awt.Color(225, 225, 225));
        jtxtInput.setSelectedTextColor(new java.awt.Color(225, 225, 225));
        jtxtInput.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtxtInputKeyTyped(evt);
            }
        });

        jbttnRemoveLast.setBackground(new java.awt.Color(20, 20, 20));
        jbttnRemoveLast.setForeground(new java.awt.Color(225, 225, 225));
        jbttnRemoveLast.setText("Remove Last Item");
        jbttnRemoveLast.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbttnRemoveLastActionPerformed(evt);
            }
        });

        jbttnAddItem.setBackground(new java.awt.Color(20, 20, 20));
        jbttnAddItem.setForeground(new java.awt.Color(225, 225, 225));
        jbttnAddItem.setText("Add Item");
        jbttnAddItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbttnAddItemActionPerformed(evt);
            }
        });

        jbttnRemoveSelected.setBackground(new java.awt.Color(20, 20, 20));
        jbttnRemoveSelected.setForeground(new java.awt.Color(225, 225, 225));
        jbttnRemoveSelected.setText("Remove Selected");
        jbttnRemoveSelected.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbttnRemoveSelectedActionPerformed(evt);
            }
        });

        jlblSelected.setBackground(new java.awt.Color(20, 20, 20));
        jlblSelected.setForeground(new java.awt.Color(225, 225, 225));
        jlblSelected.setText("Selected Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtInput)
                            .addComponent(jcmboComedians, 0, 157, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttnRemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttnRemoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlblSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmboComedians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnRemoveLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttnRemoveSelected)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttnRemoveLastActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbttnRemoveLastActionPerformed
    {//GEN-HEADEREND:event_jbttnRemoveLastActionPerformed
        int cNums = 0;
       
       
        try
        {
            cNums = jcmboComedians.getItemCount();
            jcmboComedians.removeItemAt(cNums - 1);
        }
        catch (Exception e)
        {
            
        }
       
       
    }//GEN-LAST:event_jbttnRemoveLastActionPerformed

    private void jbttnAddItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbttnAddItemActionPerformed
    {//GEN-HEADEREND:event_jbttnAddItemActionPerformed

        AddToList();
        
        
    }//GEN-LAST:event_jbttnAddItemActionPerformed

    private void jbttnRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbttnRemoveSelectedActionPerformed
    {//GEN-HEADEREND:event_jbttnRemoveSelectedActionPerformed
        // TODO add your handling code here:
        
        int xRemoveItem = -1;
        
        xRemoveItem = jcmboComedians.getSelectedIndex();
        
        if (xRemoveItem > -1)
        {
            jcmboComedians.removeItemAt(xRemoveItem);
        }
        
    }//GEN-LAST:event_jbttnRemoveSelectedActionPerformed

    private void jtxtInputKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtInputKeyTyped
    {//GEN-HEADEREND:event_jtxtInputKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
            AddToList();
        }
    }//GEN-LAST:event_jtxtInputKeyTyped

    private void jcmboComediansActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcmboComediansActionPerformed
    {//GEN-HEADEREND:event_jcmboComediansActionPerformed
        // TODO add your handling code here:
        jlblSelected.setText(String.valueOf(jcmboComedians.getSelectedItem()));
       
    }//GEN-LAST:event_jcmboComediansActionPerformed

    
    void AddToList()
    {
        if(jtxtInput.getText().length() > 0)
        {
            jcmboComedians.addItem(jtxtInput.getText());
            
            jtxtInput.setText(null);
        }
    }
/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
    public void run()
    {
        new Frame1().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbttnAddItem;
    private javax.swing.JButton jbttnRemoveLast;
    private javax.swing.JButton jbttnRemoveSelected;
    private javax.swing.JComboBox<String> jcmboComedians;
    private javax.swing.JLabel jlblSelected;
    private javax.swing.JTextField jtxtInput;
    // End of variables declaration//GEN-END:variables
}
