/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scrollers;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Collin Shook
 */
public class Frame1 extends javax.swing.JFrame {

    BufferedImage image;
    
    ImageIcon myImage;
    
    ScrollingPic thePix = new ScrollingPic();
    ScrollingPic thePix2 = new ScrollingPic();
    
    
    int xPos;
    int yPos;
    
    Timer myTimer;
    
    /**
     * Creates new form FrameStart
     */
    public Frame1() {
        initComponents();
        
        xPos = 0;
        yPos = 0;
        
        thePix.setVisible(true);
        thePix2.setVisible(true);
        
        thePix.setSize(3000, 300);
        thePix2.setSize(3000, 300);
        
        thePix.setLocation(0, 0);
        thePix2.setLocation(3000, 0);
        
        jPViewer.setSize(500, 300);
        
        jPViewer.add(thePix);
        jPViewer.add(thePix2);
        
        
        StartAnimation();
        
    }

    
    void StartAnimation()
    {
        myTimer = new Timer(1, new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                xPos -= 3;
             
                thePix.setLocation(xPos, yPos);
                thePix2.setLocation(xPos + 3000, yPos);
                
                if(xPos <= -3000)
                {
                    xPos = 0;
                }
                
                
            }
            
        });
        
        myTimer.start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPViewer = new javax.swing.JPanel();
        jBttnToggleScroll = new javax.swing.JButton();
        jBttnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPViewerLayout = new javax.swing.GroupLayout(jPViewer);
        jPViewer.setLayout(jPViewerLayout);
        jPViewerLayout.setHorizontalGroup(
            jPViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPViewerLayout.setVerticalGroup(
            jPViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jBttnToggleScroll.setText("Start / Stop");
        jBttnToggleScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnToggleScrollActionPerformed(evt);
            }
        });

        jBttnHome.setText("Home");
        jBttnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBttnToggleScroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBttnHome)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnToggleScroll)
                    .addComponent(jBttnHome))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnToggleScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnToggleScrollActionPerformed
        // TODO add your handling code here:
        if( myTimer.isRunning())
        {
            myTimer.stop();
        }
        else
        {
            myTimer.start();
        }
    }//GEN-LAST:event_jBttnToggleScrollActionPerformed

    private void jBttnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnHomeActionPerformed
        // TODO add your handling code here:
        Scrollers.InitMainFrame();
        
        this.dispose();
    }//GEN-LAST:event_jBttnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnHome;
    private javax.swing.JButton jBttnToggleScroll;
    private javax.swing.JPanel jPViewer;
    // End of variables declaration//GEN-END:variables
}
