/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sliders;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author collinshook
 */
public class Frame1 extends javax.swing.JFrame
{

static int ProgValue;
Timer myTimer;
Timer myShowTime;
Color myColor;

SimpleDateFormat myDateFormat;
Date myDate;
/**
 * Creates new form Frame1
 */


public Frame1()
{
    initComponents();
    
    
    // create a color
    myColor = new Color(102, 0, 102);
    
    
    // slider
    jsldr1.setMajorTickSpacing(100);
    jsldr1.setMinorTickSpacing(20);
    jsldr1.setMaximum(500);
    jsldr1.setMinimum(100);
    jsldr1.setValue(200);
    
    jsldr1.setPaintTicks(true);
    jsldr1.setOpaque(true);
    jsldr1.setBackground(myColor);
    jsldr1.setPaintLabels(true);
    jsldr1.setPaintTrack(true);

    // progress bar
    ProgValue = 0;
    
    jprogress1.setMinimum(0);
    jprogress1.setMaximum(100);
    jprogress1.setStringPainted(true);
    jprogress1.setValue(ProgValue);
    
    ShowTime();
}



private void ShowTime()
{
    myTimer = new Timer(1000, new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            myDateFormat = new SimpleDateFormat("hh:mm:ss a");
            myDate = new Date();
            
            jlblClock.setText(myDateFormat.format(myDate));
        }
    });
    
    myTimer.start();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jsldr1 = new javax.swing.JSlider();
        jprogress1 = new javax.swing.JProgressBar();
        jlblValue = new javax.swing.JLabel();
        jlblClock = new javax.swing.JLabel();
        jbttnStart = new javax.swing.JButton();
        jbttnStop = new javax.swing.JButton();
        jbttnReset = new javax.swing.JButton();
        jbttnStopClock = new javax.swing.JButton();
        jbttnStartClock = new javax.swing.JButton();
        jtxtClock = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsldr1.setBackground(new java.awt.Color(20, 20, 20));
        jsldr1.setForeground(new java.awt.Color(225, 225, 225));
        jsldr1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jsldr1.addInputMethodListener(new java.awt.event.InputMethodListener()
        {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt)
            {
                jsldr1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt)
            {
            }
        });

        jprogress1.setBackground(new java.awt.Color(20, 20, 20));
        jprogress1.setForeground(new java.awt.Color(51, 255, 51));
        jprogress1.setToolTipText("");
        jprogress1.setValue(23);
        jprogress1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblValue.setBackground(new java.awt.Color(20, 20, 20));
        jlblValue.setForeground(new java.awt.Color(225, 225, 225));
        jlblValue.setText("Value");

        jlblClock.setBackground(new java.awt.Color(20, 20, 20));
        jlblClock.setForeground(new java.awt.Color(225, 225, 225));
        jlblClock.setText("Clock");

        jbttnStart.setBackground(new java.awt.Color(20, 20, 20));
        jbttnStart.setForeground(new java.awt.Color(225, 225, 225));
        jbttnStart.setText("Start");

        jbttnStop.setBackground(new java.awt.Color(20, 20, 20));
        jbttnStop.setForeground(new java.awt.Color(225, 225, 225));
        jbttnStop.setText("Stop");

        jbttnReset.setBackground(new java.awt.Color(20, 20, 20));
        jbttnReset.setForeground(new java.awt.Color(225, 225, 225));
        jbttnReset.setText("Reset");

        jbttnStopClock.setBackground(new java.awt.Color(20, 20, 20));
        jbttnStopClock.setForeground(new java.awt.Color(225, 225, 225));
        jbttnStopClock.setText("Stop");

        jbttnStartClock.setBackground(new java.awt.Color(20, 20, 20));
        jbttnStartClock.setForeground(new java.awt.Color(225, 225, 225));
        jbttnStartClock.setText("Start");

        jtxtClock.setBackground(new java.awt.Color(20, 20, 20));
        jtxtClock.setForeground(new java.awt.Color(225, 225, 225));
        jtxtClock.setText("jTextField1");

        jMenuBar1.setBackground(new java.awt.Color(10, 10, 10));

        jMenu1.setBackground(new java.awt.Color(10, 10, 10));
        jMenu1.setForeground(new java.awt.Color(225, 225, 225));
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setBackground(new java.awt.Color(10, 10, 10));
        jMenuItem1.setForeground(new java.awt.Color(225, 225, 225));
        jMenuItem1.setText("Quit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jprogress1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbttnStartClock)
                        .addGap(18, 18, 18)
                        .addComponent(jbttnStopClock)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jsldr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jbttnStart)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbttnStop)
                                .addGap(18, 18, 18)
                                .addComponent(jbttnReset)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jlblValue)
                                .addGap(36, 36, 36)
                                .addComponent(jlblClock)
                                .addGap(57, 57, 57))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsldr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblValue)
                        .addComponent(jlblClock)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttnStart)
                    .addComponent(jbttnStop)
                    .addComponent(jbttnReset))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbttnStartClock)
                        .addComponent(jbttnStopClock))
                    .addComponent(jprogress1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jtxtClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsldr1CaretPositionChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_jsldr1CaretPositionChanged
    {//GEN-HEADEREND:event_jsldr1CaretPositionChanged
        // TODO add your handling code here:
        jlblValue.setText(String.valueOf(jsldr1.getValue()));
    }//GEN-LAST:event_jsldr1CaretPositionChanged

/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
    public void run()
    {
        new Frame1().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbttnReset;
    private javax.swing.JButton jbttnStart;
    private javax.swing.JButton jbttnStartClock;
    private javax.swing.JButton jbttnStop;
    private javax.swing.JButton jbttnStopClock;
    private javax.swing.JLabel jlblClock;
    private javax.swing.JLabel jlblValue;
    private javax.swing.JProgressBar jprogress1;
    private javax.swing.JSlider jsldr1;
    private javax.swing.JTextField jtxtClock;
    // End of variables declaration//GEN-END:variables

}
